spring.config.import=file:env.properties
spring.application.name=F1-Fans-Hub-BE
#DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=${HIBERNATE_AUTO}
