spring.config.import=file:env.properties
spring.application.name=F1-Fans-Hub-BE
#DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=${HIBERNATE_AUTO}
#JWT
jwt.secret=${JWT_SECRET}
#ADMIN
admin.name=${admin.name}
admin.surname=${admin.surname}
admin.username=${admin.username}
admin.email=${admin.email}
admin.password=${admin.password}
#CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
#SPRINGMAIL
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=sabatinoprovenza@gmail.com
